# Shell variables
# Generated by 'wal'
wallpaper='/home/example/Images/wallpapers/wpA.jpg'

# Special
background='#0F130D'
foreground='#dce4d1'
cursor='#dce4d1'

# Colors
color0='#0F130D'
color1='#768966'
color2='#8B9874'
color3='#AEBC7B'
color4='#9FAF8D'
color5='#C2BDA6'
color6='#B7CAA1'
color7='#dce4d1'
color8='#9a9f92'
color9='#768966'
color10='#8B9874'
color11='#AEBC7B'
color12='#9FAF8D'
color13='#C2BDA6'
color14='#B7CAA1'
color15='#dce4d1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
