--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/example/Images/wallpapers/puprle2.jpg"

-- Special
background="#0E172E"
foreground="#f4c5ba"
cursor="#f4c5ba"

-- Colors
color0="#0E172E"
color1="#9B4F6C"
color2="#EA656E"
color3="#B78E75"
color4="#F98F7A"
color5="#70608E"
color6="#916B96"
color7="#f4c5ba"
color8="#aa8982"
color9="#9B4F6C"
color10="#EA656E"
color11="#B78E75"
color12="#F98F7A"
color13="#70608E"
color14="#916B96"
color15="#f4c5ba"
