$foreground = rgb(f4c5ba)
$color0 = rgb(0E172E)
$color1 = rgb(9B4F6C)
$color2 = rgb(EA656E)
$color3 = rgb(B78E75)
$color4 = rgb(F98F7A)
$color5 = rgb(70608E)
$color6 = rgb(916B96)
$color7 = rgb(f4c5ba)
$color8 = rgb(aa8982)
$color9 = rgb(9B4F6C)
$color10 = rgb(EA656E)
$color11 = rgb(B78E75)
$color12 = rgb(F98F7A)
$color13 = rgb(70608E)
$color14 = rgb(916B96)
$color15 = rgb(f4c5ba)
