--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/example/Images/wallpapers/purple1.jpg"

-- Special
background="#090410"
foreground="#f5e4bd"
cursor="#f5e4bd"

-- Colors
color0="#090410"
color1="#A75C8B"
color2="#9F6784"
color3="#CF6187"
color4="#FA768B"
color5="#FE8E8C"
color6="#FEAE89"
color7="#f5e4bd"
color8="#ab9f84"
color9="#A75C8B"
color10="#9F6784"
color11="#CF6187"
color12="#FA768B"
color13="#FE8E8C"
color14="#FEAE89"
color15="#f5e4bd"
