# Shell variables
# Generated by 'wal'
wallpaper='/home/example/Images/wallpapers/purple1.jpg'

# Special
background='#090410'
foreground='#f5e4bd'
cursor='#f5e4bd'

# Colors
color0='#090410'
color1='#A75C8B'
color2='#9F6784'
color3='#CF6187'
color4='#FA768B'
color5='#FE8E8C'
color6='#FEAE89'
color7='#f5e4bd'
color8='#ab9f84'
color9='#A75C8B'
color10='#9F6784'
color11='#CF6187'
color12='#FA768B'
color13='#FE8E8C'
color14='#FEAE89'
color15='#f5e4bd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
