$foreground = rgb(dce4d1)
$color0 = rgb(0F130D)
$color1 = rgb(768966)
$color2 = rgb(8B9874)
$color3 = rgb(AEBC7B)
$color4 = rgb(9FAF8D)
$color5 = rgb(C2BDA6)
$color6 = rgb(B7CAA1)
$color7 = rgb(dce4d1)
$color8 = rgb(9a9f92)
$color9 = rgb(768966)
$color10 = rgb(8B9874)
$color11 = rgb(AEBC7B)
$color12 = rgb(9FAF8D)
$color13 = rgb(C2BDA6)
$color14 = rgb(B7CAA1)
$color15 = rgb(dce4d1)
