$foreground = rgb(f5e4bd)
$color0 = rgb(090410)
$color1 = rgb(A75C8B)
$color2 = rgb(9F6784)
$color3 = rgb(CF6187)
$color4 = rgb(FA768B)
$color5 = rgb(FE8E8C)
$color6 = rgb(FEAE89)
$color7 = rgb(f5e4bd)
$color8 = rgb(ab9f84)
$color9 = rgb(A75C8B)
$color10 = rgb(9F6784)
$color11 = rgb(CF6187)
$color12 = rgb(FA768B)
$color13 = rgb(FE8E8C)
$color14 = rgb(FEAE89)
$color15 = rgb(f5e4bd)
