--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/example/Images/wallpapers/wpA.jpg"

-- Special
background="#0F130D"
foreground="#dce4d1"
cursor="#dce4d1"

-- Colors
color0="#0F130D"
color1="#768966"
color2="#8B9874"
color3="#AEBC7B"
color4="#9FAF8D"
color5="#C2BDA6"
color6="#B7CAA1"
color7="#dce4d1"
color8="#9a9f92"
color9="#768966"
color10="#8B9874"
color11="#AEBC7B"
color12="#9FAF8D"
color13="#C2BDA6"
color14="#B7CAA1"
color15="#dce4d1"
