# Shell variables
# Generated by 'wal'
wallpaper='/home/example/Images/wallpapers/puprle2.jpg'

# Special
background='#0E172E'
foreground='#f4c5ba'
cursor='#f4c5ba'

# Colors
color0='#0E172E'
color1='#9B4F6C'
color2='#EA656E'
color3='#B78E75'
color4='#F98F7A'
color5='#70608E'
color6='#916B96'
color7='#f4c5ba'
color8='#aa8982'
color9='#9B4F6C'
color10='#EA656E'
color11='#B78E75'
color12='#F98F7A'
color13='#70608E'
color14='#916B96'
color15='#f4c5ba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
